### ISSUE TITLE
Can you achieve the effect of the login interface like ChatGPT app?

### ISSUE THREAD

**Issue by itMcdull** [dariagorlova/typewrite_text#1]
First of all, thank you for your plugin, it is very good, but I recently encountered an effect like ChatGPT, which requires a vibration every time a text appears, and a quick vibration effect when it is deleted. Is it possible? Thank you very much

https://github.com/user-attachments/assets/e8536a13-15be-4edf-a6fa-0d0bed176295

**Comment by dariagorlova** [comment]
Done. Version 1.0.1 has a vibration feature (by default - disabled). and 'needCursor' flag became a 'cursorSymbol'. Check the description on pub.dev for details. Vibration frequency depends on 'forwardAnimationDuration' and 'reverseAnimationDuration' values.

**Comment by itMcdull** [comment]
Very cool, first of all, thank you for your update, it meets my expectations. But I hope to have a callback when each element of the List in the array is switched. So that I can know when I switch to the next one. Update my background color synchronously
If I could, thank you very much.

**Comment by itMcdull** [comment]
Should the vibration when the text is retracted be smaller? I really don't understand how chatgpt is implemented.

**Comment by dariagorlova** [comment]
> Very cool, first of all, thank you for your update, it meets my expectations. But I hope to have a callback when each element of the List in the array is switched. So that I can know when I switch to the next one. Update my background color synchronously

v1.0.2. "chatgpt_clone_sample.dart" in the sample folder is what you need.

> Should the vibration when the text is retracted be smaller? I really don't understand how ChatGPT is implemented.

About vibration. Changed bool flag to enum. check how it works. As for me, there is no difference in vibration types (checked on Pixel8). To add cool vibrations I have or to add flutter packages, or to use a platform channel and write native android and ios code. The first variant is bad, cause this package will depend on the other one, second variant - I'm too lazy to do it )).

**Comment by itMcdull** [comment]
Pushing to another page does not stop HapticFeedback because dispose is not triggered

**Comment by dariagorlova** [comment]
Thank you for pointing out this bug. It's fixed in v1.0.3

**Comment by itMcdull** [comment]
Thank you, this plugin meets my needs, you are a great author
